Switches to different typescript plugin for rollup
Because the other one raised errors that I couldn't fix:

```
src/hyperpath.ts → dist, dist...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/hyperpath.ts (5:17)
3:
4: export class HyperPath {
5:   createChannel(): Channel {
                    ^
6:     return new HyperSwarmChannel()
7:   }
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/nlv19703/Documents/Projects/hyperpath/node_modules/rollup/dist/shared/rollup.js:10120:30)
```